language: node_js
node_js:
  - "12.8.0"

env:
  - BUILD_DIR=client
  - BUILD_DIR=server

script:
  - if [ "$BUILD_DIR" = "client" ]; then cd $BUILD_DIR && cd Sawaah && npm install && npm run android; fi
  - if [ "$BUILD_DIR" = "server" ]; then cd $BUILD_DIR && npm install; fi
